- name: Install packages
  apt:
    pkg:
      - iptables
      - hostapd
      - dnsmasq

- name: Configure dnsmasq
  template:
    dest: /etc/dnsmasq.d/fieldday
    src: dnsmasq
    owner: root
    group: root
    mode: 0664

- name: Configure hostapd
  template:
    dest: /etc/hostapd/hostapd.conf
    src: hostapd
    owner: root
    group: root
    mode: 0660

- name: Enable hostapd
  ansible.builtin.systemd:
    name: hostapd
    masked: false

- name: Configure interfaces
  template:
    dest: /etc/network/interfaces.d/fieldday
    src: interfaces
    owner: root
    group: root
    mode: 0664

- name: Disable DHCP client on WAP
  lineinfile:
    path: /etc/dhcpcd.conf
    line: denyinterfaces {{ wapif }}

- name: Enable IP forwarding
  lineinfile:
    path: /etc/sysctl.d/99-fieldday.conf
    line: "net.ipv4.ip_forward=1"
    create: yes

- name: Set hostname alias
  lineinfile:
    path: /etc/hosts
    line: "{{ localip }} {{ hostname }}"
    regexp: "\\s+{{ hostname }}"
  when: hostname is defined
